NewsStudyRostelecom/NewsStudyRostelecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import main.views as main_views
handler404 = main_views.custom_404
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('update_server/', main_views.update_server, name='update_server'),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('home/', include('home.urls')),
    path('users/', include('users.urls')),
             ##http://127.0.0.1:8000/
#] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug/__', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования Зеленых новостей"
admin.site.index_title = "Зеленые новости"
admin.site.index_template = 'main/custom_admin.html'

NewsStudyRostelecom/home/urls.py
from django.urls import path

from .import views
urlpatterns = [
    path('', views.index, name='demo'),
    path('demo_form/', views.demo_form),
    path('showlastmodel/', views.showlastmodel),


]

NewsStudyRostelecom/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('calc/<int:a>/<slug:operation>/<int:b>',views.get_demo),
    path('about/', views.about, name='about'),
    path('sidebar/', views.sidebar),
    path('test_page/', views.test_page),
    path('base/', views.base),
    path('custom_404/', views.custom_404),

]

NewsStudyRostelecom/main/models.py
from django.db import models

# Create your models here.
class News:
    def __init__(self, title, text, date):
        self.title = title
        self.text = text
        self.date = date

    def __str__(self):
        return f'{self.title}: {self.text}, {self.date}'


class Product:
    counter = 0
    def __init__(self,title,price,quantity):
        self.title = title
        self.price = price
        self.quantity = quantity
        Product.counter +=1

    def amount(self):
        return self.price*self.quantity

NewsStudyRostelecom/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
import datetime
from django.db.models import Count

class Tag(models.Model):
    title = models.CharField(max_length=80)
    status = models.BooleanField(default=True)
    def __str__(self):
        return self.title

    # def tag_count(self):
    #     count = self.article_set.count()
    #     # комментарий: когда мы работаем со связанными объектами (foreign_key, m2m, один к одному),
    #     # мы можем обращаться к связанным таблицам при помощи синтаксиса:
    #     # связаннаяМодель_set и что-то делать с результатами. В этом примере - мы используем связанные article
    #     # и вызываем метод count
    #     return count
    class Meta:
        ordering = ['title','status']
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'


class PublishedToday(models.Manager):
    def get_queryset(self):
        return super(PublishedToday,self).get_queryset().filter(date__gte=datetime.date.today())

class Article(models.Model):
    categories = (('A', 'Животные'),
                  ('P', 'Растения'),
                  ('M', 'Микромир'),
                  ('W', 'Вода'),
                  ('N', 'Природа'))
    #поля                                       #models.CASCADE SET_DEFAULT (совсем удалить пользователя вместе с новостями)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    #author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True) - если хотим статьи оставлять при удалении юсера
    title = models.CharField('Название', max_length=50, default='') #указывать длину обязательно#
    anouncement = models.TextField('Аннотация', max_length=250) #можно не указывать длину#
    text = models.TextField('Текст новости')
    date = models.DateTimeField('Дата публикации', auto_now=True) # auto_now=True - автоизменение новости auto_create=True - автосоздание новости#
    category = models.CharField(choices=categories, max_length=20, verbose_name='Категории')
    tags = models.ManyToManyField( to=Tag, blank=True, verbose_name='Теги')
    status = models.BooleanField(default=True)
    objects = models.Manager()
    published = PublishedToday()
    # image = models.ImageField(default='default1.jpg', null=True, blank=True, upload_to='images/')
    # slug = models.SlugField()
    # default='default1.jpg' - добавить в скобки полей для кари=тинок, если надо по умолчанию сделать дефолтную картинку

    #методы моделей
    def __str__(self):
        return f'{self.title} от: {str(self.date)[:16]}'
    def image_tag(self):
        image = Image.objects.filter(article=self)
        if image:
            return mark_safe('<img src="{}" height="50"/>'.format(image[0].image.url))
        else:
            return '(нет картинки)'

    def get_views(self):
        return self.views.count()

    class Meta:
        ordering = ['title','date']
        verbose_name= 'Новость'
        verbose_name_plural='Новости'


    def get_absolute_url(self):
        return f'/news/{self.id}' # еще допускается ключ pk#
    #
    #метаданные модели
    class Meta:
        ordering = ['date','title']
        verbose_name ='Новость'
        verbose_name_plural ='Новости'
    #
    # def tag_list(self):
    #     s = ''
    #     for t in self.tags.all():
    #         s += t.title + ' '
    #     return s

class Image(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(default='default1.jpg', null=True, upload_to='images/') #лучше добавить поле default !!!

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image is not None:
            return mark_safe(f'<img src="{self.image.url}" height="50px" width="auto" />')
        else:
            return '(нет картинки)'
    class Meta:
        ordering = ['title']
        verbose_name = 'Картинка'
        verbose_name_plural = 'Картинки'


class ViewCount(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,
                                related_name='views')
    ip_address = models.GenericIPAddressField()
    view_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-view_date',)
        indexes = [models.Index(fields=['-view_date'])]
        verbose_name = 'Просмотры'
        verbose_name_plural = 'Просмотры'

    def __str__(self):
        return self.article.title

NewsStudyRostelecom/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import News, Product
from news.models import Article
from django.db.models import Count, Avg
from django.contrib.auth.models import User
import json
import git
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import hashlib
import hmac
from django.http import HttpResponseServerError


def index (request):
    all_news = Article.objects.all().values('author','title')
    article = Article.objects.all().last()
    # for a in all_news:
    #     print(a['author'], a['title'])
    context = {'articles': all_news, 'article': article}
#     all_news = Article.objects.all().values_list('author','title')
#     for a in all_news:
#         print(a)
    # По старому:
    # article = Article.objects.get(id=1)
    # print(article.author.username)

    # Через select_related:
    # article = Article.objects.select_related('author').get(id=1)
    # print(article.author.username)

    # Через prefetch_related М2М:
    # articles= Article.objects.prefetch_related('tags').all()
    # print(articles)

# пример аннотирования и агрегации
# count_articles = User.objects.annotate(Count('article',distinct=True))
# print(count_articles)
# for user in count_articles:
#     print(user, user.article__count)

# пример аннотирования и агрегации:
#     max_article_count_user = User.objects.annotate(Count('article', distinct=True)).order_by('-article__count').first()
#     print(max_article_count_user)
#     max_article_count =  User.objects.annotate(Count('article', distinct=True)).aggregate(Max('article__count'))
#     max_article_count_user2 = User.objects.annotate(Count('article', distinct=True)).filter(article__count__exact=max_article_count['article__count__max'])
#     print(max_article_count_user2)

    # if request.method == 'POST':
    #     print('Получили post-запрос')
    #     print(request.POST)
    #     title = request.POST.get('title')
    #     price = request.POST.get('price')
    #     quantity = request.POST.get('quantity')
    #     new_product = Product(title, float(price), int(quantity))
    #     print('Создан товар: ', new_product.title, 'Общая сумма: ', new_product.amount())
    # else:
    #     print('Получили get-запрос')
    #
    # water = Product('Добрый сок', 40, 2)
    # chocolate = Product('Шоколад', 30, 1)
    # news_part = ['О животных', 'Природные явления', 'Наука и космос', 'Знаменитые люди']
    # context = {
    #     'news_part': news_part,
    #     'water': water,
    #     'chocolate': chocolate,
    #     'colors': colors,
    # }
    return render(request, 'main/index.html', context)
# def new_single (request):
#     return render(request, 'main/new_single.html')
def about (request):
    return render(request, 'main/about.html')

def sidebar (request):
    return render(request, 'main/sidebar.html')

def test_page (request):
    return render(request, 'main/test_page.html')

def get_demo(request,a,operation,b):
    if operation == 'minus':
            result = int(a) - int (b)
    elif operation == 'plus':
            result = int(a) + int(b)
    elif operation == 'multiply':
            result = int(a) * int(b)
    elif operation == 'divide':
            result = int(a) / int(b)
    else:
            return HttpResponse('Неверная команда')
    return HttpResponse(f'Вы ввели: {a} и {b} <br> Результат: {operation}:{result}')

def custom_404(request,exception):

    return render(request, 'main/custom_404.html')

# def news (request):
#     return render(request, 'main/news.html')



def base (request):
    return render(request, 'main/base.html')


def verify_signature(payload_body, secret_token, signature_header):
    """Verify that the payload was sent from GitHub by validating SHA256.

    Raise and return 403 if not authorized.

    Args:
        payload_body: original request body to verify (request.body())
        secret_token: GitHub app webhook token (WEBHOOK_SECRET)
        signature_header: header received from GitHub (x-hub-signature-256)
    """
    if not signature_header:
        return HttpResponseServerError("x-hub-signature-256 header is missing!", status=403)
    hash_object = hmac.new(secret_token.encode('utf-8'), msg=payload_body, digestmod=hashlib.sha256)
    expected_signature = "sha256=" + hash_object.hexdigest()
    if not hmac.compare_digest(expected_signature, signature_header):
        return HttpResponseServerError("Request signatures didn't match!", status=403)


@csrf_exempt
def update_server(request):
    header_signature = request.META.get('HTTP_X_HUB_SIGNATURE')
    verify_signature(request.body,settings.GITHUB_WEBHOOK_KEY,header_signature)

    if request.method == "POST":
        local_dir = '/home/Naddy777/RTK'
        repo = git.Repo(local_dir)
        repo.remotes.origin.pull()
        return HttpResponse("PythonAnywhere server updated successfully")
    else:
        return HttpResponse("Вы попали не туда")


# @csrf_exempt
# def update_server(request):
#     return HttpResponse("Хук работает")

NewsStudyRostelecom/main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %} О нас {% endblock %}

{% block content %}
<body>
<br/>
<h1 class="text-success">О нас</h1><br/><br/>
<div class="container-fluid">
  <p class="fw-bold">Наш сайт «Зеленые новости» начал работу совсем недавно.</p>
    <p class="fw-bold">Ежедневно мы добавляем интересные публикации, собранные нашими пользователями со всех уголков мира.</p>
    <p class="fw-bold">Наша Миссия - дарить читателям интересные факты, ценные и актуальные данные о мировых событиях, новых открытиях и забавных случаях в мире животных и растений.</p><br/>
  </p>
</div>
<h1 class="text-success">Контакты</h1><br/>

<div class="container-fluid">
<table  class="table table-sm">
    <tbody>
    <tr>
      <th>Адрес электронной почты редакции:</th>
      <td>ng-y@yandex.ru</td>
    </tr>
    <tr>
      <th>Телефон редакции:</th>
      <td>+7 (921) 747-74-23</td>

    </tr>
    <tr>
      <th>По вопросам размещения пресс-релизов и рекламы:</th>
      <td>+7 (991) 037-53-27</td>

    </tr>
    <tr>
      <th>Как нас найти:</th>
      <td> Санкт-Петербург ул. Большая Морская д.26 БЦ "Сенатор" (Офис №666)</td>
    </tr>
  </tbody>
</table><br/>
</div>
    <h1 class="text-success">Форма обратной связи</h1><br/>
<!--    <link rel="stylesheet" href="link_button_3.css">-->
<!--    <a href="{% url 'contact_page' %}" class="button5 bg-success rounded">-->
<!--        <i class="fa-regular fa-pen-to-square menu-icon"></i>-->
<!--        <div class="d-none d-lg-block">Напишите нам</div></a>-->
   <a href="{% url 'contact_page' %}" class="btn btn-success col-3 ">
        <i class="fa-regular fa-pen-to-square menu-icon"></i>
        <div class="d-none d-lg-block h5">Напишите нам</div></a>
</body>
{% endblock %}
</html>

NewsStudyRostelecom/main/templates/main/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<head>
    <meta charset="UTF-8">
    <title> {% block title %}Base{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <script src="https://kit.fontawesome.com/157685eaa0.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
</head>
<body class="bg-warning bg-opacity-10">
    <div class="row">
        <div class="col-3">
            <div class="sticky-top">
              {% block sidebar %}  {% include 'main/sidebar.html' %} {% endblock %}
            </div>
        </div>
        <div class="col-9">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>

NewsStudyRostelecom/main/templates/main/base_admin.html
{% load i18n static %}<!DOCTYPE html>
{% load static %}
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% block dark-mode-vars %}
  <link rel="stylesheet" href="{% static "admin/css/dark_mode.css" %}">
  <script src="{% static "admin/js/theme.js" %}" defer></script>
{% endblock %}
{% if not is_popup and is_nav_sidebar_enabled %}
  <link rel="stylesheet" href="{% static "admin/css/nav_sidebar.css" %}">
  <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
{% endif %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">
<a href="#content-start" class="skip-to-content-link">{% translate 'Skip to main content' %}</a>
<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    {% block header %}
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% translate 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% translate 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
                {% endif %}
                <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
                    {% csrf_token %}
                    <button type="submit">{% translate 'Log out' %}</button>
                </form>
                {% include "admin/color_theme_toggle.html" %}
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    {% endblock %}
    <!-- END Header -->
    {% block nav-breadcrumbs %}
      <nav aria-label="{% translate 'Breadcrumbs' %}">
        {% block breadcrumbs %}
          <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
            {% if title %} &rsaquo; {{ title }}{% endif %}
          </div>
        {% endblock %}
      </nav>
    {% endblock %}
    {% endif %}

    <div class="main" id="main">
      {% if not is_popup and is_nav_sidebar_enabled %}
        {% block nav-sidebar %}
          {% include "admin/nav_sidebar.html" %}
        {% endblock %}
      {% endif %}
      <div id="content-start" class="content" tabindex="-1">
        {% block messages %}
          {% if messages %}
            <ul class="messagelist">{% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
            {% endfor %}</ul>
          {% endif %}
        {% endblock messages %}
        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
          {% block pretitle %}{% endblock %}
          {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
          {% block content_subtitle %}{% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}{% endblock %}
          {% block content %}
            {% block object-tools %}{% endblock %}
            {{ content }}
          {% endblock %}
          {% block sidebar %}{% endblock %}
          <br class="clear">
        </div>
        <!-- END Content -->
        {% block footer %}<div id="footer"></div>{% endblock %}
      </div>
    </div>
</div>
<!-- END Container -->

<!-- SVGs -->
<svg xmlns="http://www.w3.org/2000/svg" class="base-svgs">
  <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-auto"><path d="M0 0h24v24H0z" fill="currentColor"/><path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2V4a8 8 0 1 0 0 16z"/></symbol>
  <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-moon"><path d="M0 0h24v24H0z" fill="currentColor"/><path d="M10 7a7 7 0 0 0 12 4.9v.1c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2h.1A6.979 6.979 0 0 0 10 7zm-6 5a8 8 0 0 0 15.062 3.762A9 9 0 0 1 8.238 4.938 7.999 7.999 0 0 0 4 12z"/></symbol>
  <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-sun"><path d="M0 0h24v24H0z" fill="currentColor"/><path d="M12 18a6 6 0 1 1 0-12 6 6 0 0 1 0 12zm0-2a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM11 1h2v3h-2V1zm0 19h2v3h-2v-3zM3.515 4.929l1.414-1.414L7.05 5.636 5.636 7.05 3.515 4.93zM16.95 18.364l1.414-1.414 2.121 2.121-1.414 1.414-2.121-2.121zm2.121-14.85l1.414 1.415-2.121 2.121-1.414-1.414 2.121-2.121zM5.636 16.95l1.414 1.414-2.121 2.121-1.414-1.414 2.121-2.121zM23 11v2h-3v-2h3zM4 11v2H1v-2h3z"/></symbol>
</svg>
<!-- END SVGs -->
</body>
</html>

NewsStudyRostelecom/main/templates/main/custom_404.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_javascript %}
{% block title %} Нет страницы {% endblock %}
{% block content %}
<div class="row">
    <div class="single_news bg-warning bg-opacity-10">
        <div class="p-4 p-md-5 border rounded">
            <h1 class="display-6 fst-italic"> Такой страницы не существует!</h1>
        </div>
    </div>
</div>
</br>
<div class="row">
    <div class="single_news bg-warning bg-opacity-10">

            <h1> Но есть много других! </h1>
            <a class="ml-2" href="{% url 'news_index' %}"><h1> Жми сюда!</h1></a>

    </div>
</div>



{% endblock %}

NewsStudyRostelecom/main/templates/main/custom_admin.html
{% extends "main/base_admin.html" %}
{% load static %}
{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}
{% block extrastyle %} <link rel="stylesheet" href="{% static 'main/css/style.css' %}">{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Django administration') }}</a></h1>
{% if user.is_anonymous %}
  {% include "admin/color_theme_toggle.html" %}
{% endif %}
{% endblock %}

{% block nav-global %}{% endblock %}

NewsStudyRostelecom/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %} Главная страница {% endblock %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<div class="row ">
    <div class="text-center" style="margin-top:30px;">
        <h2 class="text-success">Главные события нашей Зеленой Планеты 24 часа в сутки!</h2>
    </div>
    <div class="text-center" style="margin-top:30px;">
        <h3>Интересные новости про обитателей флоры и фауны, живые истории, оригинальные фото и видео со всех уголков мира</h3>
    </div>
    <div class="container-fluid">
        <div class="row align-items-center">
                <div class="col-sm-4" >
                    <img src="{% static 'main/img/colibri.jpg' %}" alt="Колибри"
                         class=" img-responsive img-fluid rounded">
                </div>
                <div class="col-sm-4">
                    <img src="{% static 'main/img/dolphins.jpg' %}" alt="Дельфины"
                         class="img-responsive img-fluid rounded">
                </div>
                <div class="col-sm-4">
                    <img src="{% static 'main/img/lion.jpg' %}" alt="Лев" class="img-responsive img-fluid rounded">
                </div>
        </div>
    </div>
</div>
<div class="single_news" >
    <div class="bg-warning bg-opacity-10 p-4 px-md-5 border rounded" >
        <div class="row text-end px-0">
            <h2 class="display-6 fst-italic text-success">Последняя новость сайта. Выложил пользователь: {{ article.author }} </h2>
        </div>
        <div class="row">
            <div class="col-8 px-0">
                <h1 class="display-6 fst-italic text-success fw-bold"> {{ article.title }}</h1>
                <div class="row">
                    <div class="col-md-4 lead px-0 my-3">Дата: {{ article.date }}</div>
                    <div class="col-md-3 lead px-0 my-3 text-end">Автор: {{ article.author }} </div>
                    <div class="col-md-5 lead px-0 my-3 text-end">Категория новости: {{ article.get_category_display }} </div>
                </div>
                <p class="lead my-3">{{ article.anouncement }}</p>
                <p class="lead mb-0"><a href="{{ article.get_absolute_url }}" class="text-black fw-bold">Полный текст...</a></p>
                   <br>
                <a class="btn btn-success text-start col-3" href="{% url 'favorites' article.id %}">
                    <i class="fa-solid fa-heart menu-icon"></i>
                    <div class="d-none d-lg-block"> В избранное</div>
                </a>
                 <p><small>Просмотры: {{ article.get_views }}</small></p>
            </div>
            <div class="col-4 ">
                {% if article.image_set.all %}
                <div id="carouselControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox" style=" width:auto; height: 300px !important;">
                        {% for image in article.image_set.all %}
                        <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                            <img class="d-block p-4 img-responsive img-fluid rounded" src="{{ image.image.url }}">
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {% endif%}
            </div>
        </div>
    </div>
</div>
{% endblock %}